name: 'my_dbt_project'
version: '1.0'
config-version: 2

profile: 'my_dbt_project'  # Referência ao perfil configurado no profiles.yml

model-paths: ["models"]  # Correção do source-paths
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

models:
  my_dbt_project:
    +materialized: view

