version: 2

sources:
  - name: public
    schema: public
    description: "Schema público do banco de dados"
    tables:
      - name: f_titulosemaberto
        description: "Tabela de títulos em aberto"
      - name: f_titulosemaberto_fidc  # <- Adicionado aqui
        description: "Tabela de títulos em aberto do FIDC"
      - name: d_cedentes_fidc
        description: "Tabela de cedentes"
      - name: d_sacados_fidc
        description: "Tabela de sacados"
      - name: d_sacados
        description: "Tabela de sacados"
      - name: f_operacoes
        description: "Tabela de operações"
      - name: f_operacoes_fidc
        description: "Tabela de operações do FIDC"
      - name: f_operacoes_detalhes
        description: "Tabela de detalhes das operações"
      - name: f_operacoes_fidc_detalhes
        description: "Tabela de detalhes das operações do FIDC"
     

